markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true

permalink: /:title.html

meta:
  title: Rico Sta. Cruz
  author: Rico Sta. Cruz
  name: Rico Sta. Cruz
  hostname: ricostacruz.com

facebook:
  app_id: 169204529787544
  admin: ricostacruz

analytics:
  id: "UA-20473929-1"
